### ISSUE TITLE
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/one-yolov5#109]
## 问题描述 
`python -m oneflow.distributed.launch ` 方式启动项目中 `segmet/train.py` 报错，TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:， 具体报错信息如下

## 报错信息
```shell
     Epoch    GPU_mem   box_loss   seg_loss   obj_loss   cls_loss  Instances       Size

  0%|          | 0/8 [00:00<?, ?it/s]
  0%|          | 0/8 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "segment/train.py", line 644, in <module>
    main(opt)
  File "segment/train.py", line 540, in main
    train(opt.hyp, opt, device, callbacks)
  File "segment/train.py", line 295, in train
    pred = model(imgs)  # forward
  File "/data/dataset/fengwen/package/oneflow/python/oneflow/nn/modules/module.py", line 175, in __call__
    result = hook(self, args, res)
  File "/data/dataset/fengwen/package/oneflow/python/oneflow/nn/parallel/distributed.py", line 207, in post_forward_hook
    convert_to_tensor_tuple(
  File "/data/dataset/fengwen/package/oneflow/python/oneflow/framework/tensor_tuple_util.py", line 27, in convert_to_tensor_tuple
    return TensorTuple(args)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. oneflow._oneflow_internal.TensorTuple()
    2. oneflow._oneflow_internal.TensorTuple(arg0: oneflow._oneflow_internal.TensorTuple)
    3. oneflow._oneflow_internal.TensorTuple(arg0: List[tensor])

Invoked with: [[tensor([[[[[ 1.24156e+00,  1.99916e+00,  5.01154e-01,  ..., -1.57864e-01, -1.14477e+00,  2.84494e-01],
           [ 1.02014e-01,  2.76693e+00,  1.46843e+00,  ...,  1.36876e-01, -1.57232e+00,  3.52844e-01],....
```

<details open>
<summary> /data/dataset/fengwen/package/oneflow/python/oneflow/framework/tensor_tuple_util.py </summary>

![image](https://user-images.githubusercontent.com/109639975/216893696-d512c49c-87ad-4fdf-b7f3-6c43fca22870.png)

</details>

## 环境信息
- 机器 oneflow27-root (8GPU NVIDIA GeForce RTX 3090, 24268MiB)
- oneflow版本： 2023-02-05编译的oneflow: commit 30d370c3a4586610c230edb4bae2039798923520 (HEAD -> master, origin/master, origin/HEAD)

**Comment by ccssu** [comment]
`/data/dataset/fengwen/package/oneflow/python/oneflow/framework/tensor_tuple_util.py` 中 args,
## 直接python启动  args = 
[<class 'oneflow.Tensor'>]
## python -m oneflow.distributed.launch  方式启动 args = 
[<class 'list'>,<class 'oneflow.Tensor'>,<class 'oneflow.nn.Parameter'>,<class 'oneflow.nn.Parameter'>....]
