### ISSUE TITLE
fuse bn之后nn.Graph编译失败

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/one-yolov5#20]
下面的最小复现代码可以说明这个问题，如果注释掉 delattr(m, "bn") 之后是可以正常编译的，如果加上就会报错：

```python
import oneflow as flow
import oneflow.nn as nn

class ConvBNModule(nn.Module):
    def __init__(self):
        super(ConvBNModule, self).__init__()
        self.conv = nn.Conv2d(1, 2, 1, 1)
        self.bn = nn.BatchNorm2d(2)
    
    def forward(self, x):
        return self.bn(self.conv(x))
        

m = ConvBNModule()
delattr(m, "bn")

class YOLOGraph(flow.nn.Graph):
    def __init__(self, m):
        super().__init__()
        self.model = m

    def build(self, x):
        return self.model(x)
        
yolo_graph = YOLOGraph(m)
yolo_graph._compile(flow.randn(1, 1, 3, 3))

```

报错信息：

```shell
[ERROR](GRAPH:YOLOGraph_0:YOLOGraph) building graph got error.
Traceback (most recent call last):
  File "debug.py", line 26, in <module>
    yolo_graph._compile(flow.randn(1, 1, 3, 3))
  File "/home/zhangxiaoyu/oneflow/python/oneflow/nn/graph/graph.py", line 779, in _compile
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/home/zhangxiaoyu/oneflow/python/oneflow/nn/graph/graph.py", line 798, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/home/zhangxiaoyu/oneflow/python/oneflow/nn/graph/graph.py", line 902, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "debug.py", line 23, in build
    return self.model(x)
  File "/home/zhangxiaoyu/oneflow/python/oneflow/nn/graph/block.py", line 248, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/zhangxiaoyu/oneflow/python/oneflow/nn/graph/block.py", line 280, in __block_forward
    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "debug.py", line 11, in forward
    return self.bn(self.conv(x))
  File "/home/zhangxiaoyu/oneflow/python/oneflow/nn/graph/block.py", line 519, in __getattr__
    raise AttributeError(
AttributeError: 'MODULE' 'ModuleBlock' object 'model' in nn.Graph has no attribute 'bn'
```

@strint 可以看一下

**Comment by strint** [comment]
def forward(self, x):
        return self.bn(self.conv(x))  # 这里再调用bn，出错是符合预期的
        

m = ConvBNModule()
delattr(m, "bn") # 这里把 bn 删掉了

**Comment by BBuf** [comment]
在yolov5的fuse bn里面，原始代码实现如下：

```python
class Conv(nn.Module):
    # Standard convolution
    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True):  # ch_in, ch_out, kernel, stride, padding, groups
        super().__init__()
        self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False)
        self.bn = nn.BatchNorm2d(c2)
        self.act = nn.SiLU() if act is True else (act if isinstance(act, nn.Module) else nn.Identity())

    def forward(self, x):
            return self.act(self.bn(self.conv(x)))

    def forward_fuse(self, x):
        return self.act(self.conv(x))
```

然后做fuse conv和bn时，会删除bn，并将foward覆盖为forward_fuse:

```
def fuse(self):  # fuse model Conv2d() + BatchNorm2d() layers
        LOGGER.info("Fusing layers... ")
        for m in self.model.modules():
            if isinstance(m, (Conv, DWConv)) and hasattr(m, "bn"):
                m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
                delattr(m, "bn")  # remove batchnorm
                m.forward = m.forward_fuse  # update forward
        self.info()
        return self
```

但这样获得的fuse后的nn.Module对象在被nn.Graph捕获和编译时，仍然会使用原始的forward(也就是说 m.forward = m.forward_fuse对nn.Graph没有生效)，导致报nn.Module没有相关属性的错误，这个后需要解决一下。目前通过在Conv Module的实现中加一个is_fuse参数，并在forward里面特判先饶过这个问题。

```python
class Conv(nn.Module):
    # Standard convolution
    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True):  # ch_in, ch_out, kernel, stride, padding, groups
        super().__init__()
        self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False)
        self.bn = nn.BatchNorm2d(c2)
        self.act = nn.SiLU() if act is True else (act if isinstance(act, nn.Module) else nn.Identity())
        self.is_fuse = False

    def forward(self, x):
        if not self.is_fuse:
            return self.act(self.bn(self.conv(x)))
        else:
            return self.act(self.conv(x))

    def forward_fuse(self, x):
        return self.act(self.conv(x))
```

**Comment by BBuf** [comment]
> 和这一行的处理有关：https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/nn/graph/block.py#L280
> 
> ```
> result = self._origin.__class__.forward(self, *args, **kwargs)
> ```
> 
> 那个 forward 改写没有生效

👍
