### ISSUE TITLE
eager module有free eager tensor时访问graph.state_dict()会挂掉

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/one-yolov5#23]
复现代码：

```python
import oneflow as flow
import oneflow.nn as nn

class ConvModule(nn.Module):
    def __init__(self):
        super(ConvModule, self).__init__()
        self.zero = flow.zeros(1, 2, 3, 3)
        self.conv = nn.Conv2d(1, 2, 1, 1)
    
    def forward(self, x):
        return self.conv(x) + self.zero
        

m = ConvModule()

class YOLOGraph(flow.nn.Graph):
    def __init__(self, m):
        super().__init__()
        self.model = m

    def build(self, x):
        return self.model(x)
        
yolo_graph = YOLOGraph(m)
yolo_graph._compile(flow.randn(1, 1, 3, 3))
print(yolo_graph.state_dict())
```

**Comment by strint** [comment]
错误栈是什么呢？

哪个是free eager tensor？

**Comment by BBuf** [comment]
> 错误栈是什么呢？
> 
> 哪个是free eager tensor？
> 
> 看到了，那个zero

嗯，是的。

**Comment by strint** [comment]
这个 zero 的 tensor，实际不需要保存对吧。

每一轮迭代都是 zero ？

**Comment by BBuf** [comment]
> 这个 zero 的 tensor，实际不需要保存对吧。
> 
> 它也不是参数，也不会被 inplace 修改，每一轮迭代都是一样的 ？

嗯，是的。

**Comment by strint** [comment]
在 https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/nn/graph/graph.py#L365 处，加上 skip 处理下
```
        if self._is_compiled:
            # Get from _c_nn_graph.
            additional_var_names = self._c_nn_graph.additional_var_names
            additional_var_tensors = self._c_nn_graph.additional_var_tensors
            assert len(additional_var_names) == len(additional_var_tensors)
            for i in range(len(additional_var_names)):
                # 补一下下面三行代码，用名字判断下，跳过 free eager tensor 导出到 state dict
                if "FreeEagerTensor" in additional_var_names[i]:
                    # Skip free eager tensor
                    continue
```

**Comment by BBuf** [comment]
说一下这个issue的后续，当上面的代码尝试导出onnx时：

```python
import oneflow as flow
import oneflow.nn as nn
from oneflow_onnx.oneflow2onnx.util import export_onnx_model

class ConvModule(nn.Module):
    def __init__(self):
        super(ConvModule, self).__init__()
        self.zero = flow.zeros(1, 2, 3, 3)
        self.conv = nn.Conv2d(1, 2, 1, 1)
    
    def forward(self, x):
        return self.conv(x) + self.zero
        

m = ConvModule()

class YOLOGraph(flow.nn.Graph):
    def __init__(self, m):
        super().__init__()
        self.model = m

    def build(self, x):
        return self.model(x)
        
yolo_graph = YOLOGraph(m)
yolo_graph._compile(flow.randn(1, 1, 3, 3))
print(yolo_graph.state_dict())

export_onnx_model(yolo_graph, onnx_model_path="/tmp")
```

报错如下：

```shell
Traceback (most recent call last):
  File "../debug.py", line 29, in <module>
    export_onnx_model(yolo_graph, onnx_model_path="/tmp")
  File "/home/zhangxiaoyu/oneflow_convert/oneflow_onnx/oneflow2onnx/util.py", line 61, in export_onnx_model
    Export(
  File "/home/zhangxiaoyu/oneflow_convert/oneflow_onnx/oneflow2onnx/flow2onnx.py", line 255, in Export
    model_proto = onnx_graph.MakeModel("tmp", onnx_filename, external_data=external_data)
  File "/home/zhangxiaoyu/oneflow_convert/oneflow_onnx/onnx_wrapper.py", line 957, in MakeModel
    graph = self.MakeGraph(graph_doc, onnx_filename, graph_name=graph_name, external_data=external_data)
  File "/home/zhangxiaoyu/oneflow_convert/oneflow_onnx/onnx_wrapper.py", line 928, in MakeGraph
    tensor = util.TensorProtoFromNumpy(op.get_tensor_value(as_list=False), tensor_name, external_data=external_data, export_path=onnx_filename,)
  File "/home/zhangxiaoyu/oneflow_convert/oneflow_onnx/onnx_wrapper.py", line 260, in get_tensor_value
    t = self.graph.get_saved_tensor(self)
  File "/home/zhangxiaoyu/oneflow_convert/oneflow_onnx/onnx_wrapper.py", line 797, in get_saved_tensor
    tensor_value = self._param_dict[key[: key.rfind("out") - 1]].numpy().reshape(self.get_shape(tensor_name)).astype(dtype=util.Onnx2NumpyDtype(self.get_dtype(tensor_name)))
KeyError: ''
```

这个错误的原因是因为free eager tensor做为一个const类型的op，在oneflow->onnx的逻辑中会去找这个op对应保存的权重，但实际上它是没有权重的这样就造成了错误。

**Comment by strint** [comment]
嗯，那这个 free eager tensor，是应该保存权重呢？

看起来，转成推理时，还是需要保存的，这样才能正确的执行，因为 onnx 那边是没有 eager 代码的。

**Comment by BBuf** [comment]
> 嗯，那这个 free eager tensor，是应该保存权重呢？
> 
> 看起来，转成推理时，还是需要保存的，这样才能正确的执行，因为 onnx 那边是没有 eager 代码的。

是的，有办法保存么？

**Comment by strint** [comment]
```
        if self._is_compiled:
            # Get from _c_nn_graph.
            additional_var_names = self._c_nn_graph.additional_var_names
            additional_var_tensors = self._c_nn_graph.additional_var_tensors
            assert len(additional_var_names) == len(additional_var_tensors)
            for i in range(len(additional_var_names)):
                additional_tensor = additional_var_tensors[I]
                // 增加一个 additional_tensor.is_global 的判断
                if not self._is_global_view and additional_tensor.is_global:
                    additional_tensor = additional_tensor.to_local()
                destination[additional_var_names[i]] = additional_tensor
```
